universe = docker
docker_image = dockerreg.chtc.wisc.edu/dhoconno/mhc-from-mes:25561

# separate output into subfolders
# need to create output folder structure first (use create_output_folders.py)
# need to use initialdir to do this
# also need to specify path to parent folder where scripts and other input files reside
# make sure sample sheet has UNIX line endings and UTF-8 with BOM encoding
# otherwise a space gets inserted in the variable replacement
parentdir = /home/lyfoung/25718
initialdir = $(parentdir)/out/$(name)

# logs (path relative to intiialdir)
Error   = logs/err.$(Process)                                                                                               
Output  = logs/out.$(Process)                                                
Log     = logs/log.$(Process) 

# machine specs
requirements = (OpSysMajorVer =?= 7)
request_cpus = 1
request_memory = 6GB
request_disk = 20GB

# prioritize our machines
+AccountingGroup = "Pathology_OConnor"

# use staging large data transfer
Requirements = (Target.HasCHTCStaging == true)

# shell script to run
executable = 25625-CHTC.sh

# arguments to shell script
# do not quote path to reference genome file
Arguments = -s $(name) \
-p /staging/groups/oconnor_group/25718/reads \
-r $(sample)_R1_001.fastq.gz \
-t $(sample)_R2_001.fastq.gz \
-f $(ref_fasta) \
-e 25718

# file transfer options
# need to copy from transfer server in script

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(parentdir)/ref/$(ref_fasta), $(parentdir)/25625-CHTC.sh, $(parentdir)/25625-CHTC.snakefile

# create fastq_list of comma separated files to process
# described here: http://chtc.cs.wisc.edu/multiple-jobs.shtml
# ref_fasta is the miSeq amplicon reference

ref_fasta = Mamu_MiSeq-IPD_17.06.01_2.2.0.0_plus_SP.fasta

queue name,sample from samples.csv
